language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
env:
  - SKIP_PREFLIGHT_CHECK=true
script:
  - yarn build
  - cd example
  - yarn
  - yarn build
  - cd ../ts-example
  - yarn
  - yarn build
